dist: trusty
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.8
  - AWSCREDS_CHECKSUM=546f677ffb3824e808b2aebe0aa8c93374aba95577e6efe03e7152f05d86608b
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
- "./scripts/download_provider.sh awscreds $AWSCREDS_CHECKSUM"
- "~/tfbin/terraform init -upgrade -input=false"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
- "~/tfbin/terraform plan -detailed-exitcode -input=false"
notifications:
  email: false
  slack:
    secure: vUMOwrGgwCKbN3oykc9nblhFMAtQLYXEDRBR3ZDgDHDNLQwurRle9t4/arnGxBHLaMUy+L677y7ikFKdo7L6KEGbJW+CkU/Xy6uHcSNkGwE8fjxWCML9fy7pmvsV4o/5JVG6irkWlwBsie2jCh4uwUHLlJRE3VACNgwJheMXkJqxFxIF0LcL245xw3/vPfrKstPzgMOf/wDdLy6Npejgxj2Cjqw5M/W+H012FlDRBX6aGeA/q6/lna1+h802DAeAC15+vFDO9pjnd2zFX52luJL1fiDgSmfcuZN3KQj7SeZXF+Hoq7403Np6GQmiodOsBsui++9TXWxikodKMlMIUee4BknXJXKybH5h0aQyVX0zRsmeKSYCft1dTV9+pP+jH2WQTivFLVXQFCSGmoBwHBrp/T25TCPF03nT0GOd6OBzMBlbitJdzAmXhQ1Am7KVFSSU1kyI+WP/Ye1afS7Nz3mzKNlwMPe4R81Xv3nAzPcejbvMX/aM7f+e4vw+XG9oqwXLh0468D27fR6R8NpAG21J123jtAbg6K8xliWVbN63CcYKJcv8xM4ZTNhhHoAXGWGPIcGo8B07EP5WDt5+laycgxAXZ9G7CmMi/py8YqlYzyUfHUH3pbO4ZUq5WENiml73otnbR2E0v8GB1YiclPOCq9yyTh5J4YKPrx3qEjk=
