language: ruby
before_install:
- sudo apt-get update
- sudo apt-get install bind9
notifications:
  email: false
  irc:
    channels:
    - irc.oftc.net#akerl
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
